import make from "./module/make"

export default await make({
	"core/date/is-saturday":
		import("./date/is-saturday"),
	"core/date/is-sunday":
		import("./date/is-sunday"),
	"core/equals":
		import("./equals"),
	"core/expects":
		import("./expects"),
	"core/gender/list":
		import("./gender/list"),
	"core/japan/date/from":
		import("./japan/date/from"),
	"core/japan/hiragana/from":
		import("./japan/hiragana/from"),
	"core/japan/halfwidth-kana/from":
		import("./japan/halfwidth-kana/from"),
	"core/json-schema/validate":
		import("./json-schema/validate"),
	"core/log/error":
		import("./log/error"),
	"core/log/info":
		import("./log/info"),
	"core/map/from":
		import("./map/from"),
	"core/map/get":
		import("./map/get"),
	"core/map/keys":
		import("./map/keys"),
	"core/object/keys":
		import("./object/keys"),
	"core/override":
		import("./override"),
	"core/parallel":
		import("./parallel"),
	"core/random/integer":
		import("./random/integer"),
	"core/random/pop":
		import("./random/pop"),
	"core/random/choose":
		import("./random/choose"),
	"core/random/choose-with-ratio":
		import("./random/choose-with-ratio"),
	"core/rpc":
		import("./rpc"),
	"core/rpc/request/schema":
		import("./rpc/request/schema"),
	"core/rpc/request/validate":
		import("./rpc/request/validate"),
	"core/sample/address-and-zip/list":
		import("./sample/address-and-zip/list"),
	"core/sample/email/list":
		import("./sample/email/list"),
	"core/sample/first-name/list":
		import("./sample/first-name/list"),
	"core/sample/last-name/list":
		import("./sample/last-name/list"),
	"core/sample/phone-number/list":
		import("./sample/phone-number/list"),
	"core/serial":
		import("./serial"),
	"core/sleep":
		import("./sleep"),
	"core/task/artifact/add":
		(async () => ({ default: null as null | ((x: {url: string}) => Promise<unknown>) }))(),
	"core/task/on-screenshot":
		import("./task/on-screenshot"),
	"core/ui/form":
		import("./ui/form"),
	"core/web-browser/well-known":
		import("./web-browser/well-known"),
	"core/web-browser/active-element/blur":
		import("./web-browser/active-element/blur"),
	"core/web-browser/basic-actions":
		import("./web-browser/basic-actions"),
	"core/web-browser/basic-actions/implement":
		import("./web-browser/basic-actions/implement"),
	"core/web-browser/cursor/move-to":
		import("./web-browser/cursor/move-to"),
	"core/web-browser/element/click":
		import("./web-browser/element/click"),
	"core/web-browser/element/get":
		import("./web-browser/element/get"),
	"core/web-browser/element/list":
		import("./web-browser/element/list"),
	"core/web-browser/element/send-keys":
		import("./web-browser/element/send-keys"),
	"core/web-browser/execute-script":
		import("./web-browser/execute-script"),
	"core/web-browser/quit":
		import("./web-browser/quit"),
	"core/web-browser/start":
		import("./web-browser/start"),
	"core/web-browser/take-screenshot":
		import("./web-browser/take-screenshot"),
	"core/web-browser/load":
		import("./web-browser/load"),
	"core/web-browser/wait-for-alert-not-exists":
		import("./web-browser/wait-for-alert-not-exists"),
	"core/web-browser/wait-for-page-to-load":
		import("./web-browser/wait-for-page-to-load"),
	"core/web-browser/wait-for-number-of-windows-to-be":
		import("./web-browser/wait-for-number-of-windows-to-be"),
	"core/web-browser/window/switch":
		import("./web-browser/window/switch"),
})
